name: docker-mcp

services:
  # Docker MCP Gateway - すべてのMCPサーバーを統合
  mcp-gateway:
    image: docker/mcp-gateway:latest
    container_name: mcp-gateway
    entrypoint: ["/docker-mcp"]
    command:
      - gateway
      - run
      - --transport=sse
      - --port=9090
      - --servers=time,fetch,filesystem,git,memory,sequentialthinking
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/kazuki/github:/workspace/github:rw
      - claude-memory:/app/memory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  claude-memory:
    driver: local
