name: docker-mcp-gateway

services:
  # Docker MCP Gateway - すべてのMCPサーバーを統合
  mcp-gateway:
    image: docker/mcp-gateway:latest
    container_name: docker-mcp-gateway
    entrypoint: ["/docker-mcp"]
    command:
      - gateway
      - run
      - --transport=sse
      - --port=9090
      - --config=/etc/docker-mcp/config.json
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/kazuki/github:/workspace/github:rw
      - claude-memory:/app/memory
      - ./mcp-config.json:/etc/docker-mcp/config.json:ro
      - ./figma-catalog.yaml:/etc/docker-mcp/figma-catalog.yaml:ro
    env_file:
      - .env
    environment:
      - DOCKER_MCP_SERVERS=time,fetch,git,memory,sequentialthinking
    labels:
      - "x-secret:STRIPE_API_KEY=/run/secrets/stripe_key"
      - "x-secret:TWILIO_ACCOUNT_SID=/run/secrets/twilio_sid"
      - "x-secret:TWILIO_API_KEY=/run/secrets/twilio_key"
      - "x-secret:TWILIO_API_SECRET=/run/secrets/twilio_secret"
      - "x-secret:FIGMA_ACCESS_TOKEN=/run/secrets/figma_token"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  claude-memory:
    driver: local
