# ==========================================
# Dual-Access Strategy (CLAUDE.md準拠)
# ==========================================
# 1. ポート直接アクセス: localhost:5173
# 2. Traefikドメイン: settings.airis.traefik

services:
  settings-ui:
    networks:
      - default
      - traefik  # external: true (無ければ警告のみ)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airis-settings.rule=Host(`settings.airis.traefik`)"
      - "traefik.http.routers.airis-settings.entrypoints=web"
      - "traefik.http.services.airis-settings.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
    name: traefik-network
    # If traefik-network doesn't exist, service will start with port-only access
