"""Tool-list response shaping for the MCP proxy.

The MCP Gateway returns a verbose ``tools/list`` response with full JSON
schemas and long human descriptions. Passing that through unchanged
would burn client context on every session. This module is in charge of
rewriting those responses to be compact and consistent, and of merging
in the proxy's own tool sources (ProcessManager HOT servers, Dynamic MCP
meta-tools, and the synthetic ``expandSchema`` helper).

Three distinct responsibilities live here:

1. **Description shaping** — ``DescriptionMode`` and ``_summarize_description``
   translate a long description into "full / summary / brief / none"
   forms according to ``settings.DESCRIPTION_MODE``.
2. **Server inference** — ``_extract_server_name_from_tool`` maps a tool
   name back to the MCP server that owns it, so auto-enable heuristics
   elsewhere can look it up.
3. **Response merging** — ``apply_schema_partitioning`` and
   ``apply_prompts_merging`` consume a Gateway JSON-RPC response and
   rewrite it in place with the proxy's combined view of the world.

Keeping this isolated means the SSE transport and the JSON-RPC handler
layer only need to call one function each to get a fully shaped payload
— they never have to reach into the schema partitioner, the dynamic
MCP registry, or the process manager on their own.
"""
from __future__ import annotations

import asyncio
from typing import Any, Dict, Optional

from ...core.config import settings
from ...core.dynamic_mcp import get_dynamic_mcp
from ...core.logging import get_logger
from ...core.process_manager import get_process_manager
from ...core.schema_partitioning import schema_partitioner

logger = get_logger(__name__)


class DescriptionMode:
    """Description verbosity modes for tools/list responses."""

    FULL = "full"  # Original description (no truncation)
    SUMMARY = "summary"  # First sentence, max 160 chars (default)
    BRIEF = "brief"  # Very short, max 60 chars
    NONE = "none"  # No description (minimal tokens)


def summarize_description(
    description: str,
    mode: str = DescriptionMode.SUMMARY,
    max_length: int | None = None,
) -> str:
    """Generate a compact summary for tools/list responses.

    Args:
        description: Original description text.
        mode: One of "full", "summary", "brief", "none".
        max_length: Override max length (optional).

    Returns:
        Processed description text, or an empty string for NONE / empty
        input.
    """
    if not description:
        return ""

    if mode == DescriptionMode.NONE:
        return ""

    text = description.strip()
    if not text:
        return ""

    if mode == DescriptionMode.FULL:
        return text

    # Determine max length based on mode
    if max_length is None:
        max_length = 160 if mode == DescriptionMode.SUMMARY else 60

    # Extract first sentence across common sentence terminators
    for delimiter in [". ", "。", "！", "?", "？", "\n"]:
        idx = text.find(delimiter)
        if 0 < idx:
            if delimiter == "\n":
                text = text[:idx]
            else:
                text = text[: idx + len(delimiter.strip())]
            break

    if len(text) > max_length:
        text = text[: max_length - 1].rstrip() + "…"

    return text


def extract_server_name_from_tool(tool_name: str) -> Optional[str]:
    """Infer the MCP server that owns a tool from the tool name alone.

    Used by Dynamic MCP fallbacks where only the tool name is known and
    we need to look up (or auto-enable) the owning server. Returns
    ``None`` for built-in or ambiguous tools — the caller then falls
    back to lookups in the live registry.

    Rules:
        1. ``expandSchema`` → ``None`` (proxy-synthesised tool)
        2. Built-in tools (``get_time``, ``fetch``, ``git_*`` …) → ``None``
        3. ``prefix_verb`` style names → ``prefix`` if it is a known server
        4. Hard-coded exception tables for filesystem / serena / context7 /
           sequential-thinking / gateway-control / playwright
        5. Fallback: first underscore-separated token
    """
    if not tool_name:
        return None

    # expandSchema is a special tool (generated by Proxy)
    if tool_name == "expandSchema":
        return None

    # Built-in servers (auto-enabled via --servers at Gateway startup)
    builtin_tools = {
        "get_time", "get_current_time",
        "fetch", "fetch_url",
        "git_status", "git_diff", "git_commit", "git_push",
        "read_memory", "write_memory", "delete_memory",
    }
    if tool_name in builtin_tools:
        return None

    parts = tool_name.split("_")
    if len(parts) >= 2:
        prefix = parts[0]
        known_servers = {
            "mindbase", "github", "tavily", "stripe", "twilio",
            "supabase", "notion", "slack", "figma", "cloudflare",
            "docker", "postgres", "mongodb", "sqlite",
        }
        if prefix in known_servers:
            return prefix

    filesystem_tools = {
        "read_file", "write_file", "create_file", "delete_file",
        "list_dir", "list_directory", "search_files",
        "read_text_file", "read_media_file", "read_multiple_files",
        "edit_file",
    }
    if tool_name in filesystem_tools:
        return "filesystem"

    serena_tools = {
        "find_symbol", "find_referencing_symbols", "get_symbols_overview",
        "insert_after_symbol", "replace_symbol", "delete_symbol",
        "activate_project", "switch_modes",
    }
    if tool_name in serena_tools:
        return "serena"

    if tool_name.startswith("context7_") or tool_name in [
        "search_docs",
        "get_documentation",
    ]:
        return "context7"

    if tool_name in ["think", "sequential_think", "reasoning"]:
        return "sequential-thinking"

    if tool_name in [
        "list_mcp_servers", "enable_mcp_server", "disable_mcp_server",
        "get_mcp_server_status",
    ]:
        return "airis-mcp-gateway-control"

    if any(
        keyword in tool_name
        for keyword in ["browser", "page", "click", "navigate", "screenshot"]
    ):
        return "playwright"

    return parts[0] if parts else None


async def apply_prompts_merging(data: Dict[str, Any]) -> Dict[str, Any]:
    """Augment a ``prompts/list`` response with ProcessManager prompts.

    Mutates ``data`` in place and also returns it so call sites can chain.
    """
    if "result" not in data or "prompts" not in data["result"]:
        return data

    prompts = list(data["result"]["prompts"])

    try:
        process_manager = get_process_manager()
        process_prompts = await process_manager.list_prompts(mode="hot")
        if process_prompts:
            logger.info(
                f"Merging {len(process_prompts)} HOT prompts with {len(prompts)} docker prompts"
            )
            prompts.extend(process_prompts)
    except Exception as e:
        logger.error(f"Failed to get process prompts: {e}")

    data["result"]["prompts"] = prompts
    return data


async def _refresh_dynamic_mcp_cache(process_manager, docker_tools: list) -> None:
    """Background refresh of the Dynamic MCP cache (non-blocking)."""
    try:
        dynamic_mcp = get_dynamic_mcp()
        await dynamic_mcp.refresh_cache_hot_only(process_manager, docker_tools)

        for tool_name, tool_info in dynamic_mcp._tools.items():
            schema_partitioner.store_full_schema(tool_name, tool_info.input_schema)
            schema_partitioner.store_tool_description(tool_name, tool_info.description)

        logger.info(
            f"Background cache refresh complete: {len(dynamic_mcp._tools)} tools"
        )
    except Exception as e:
        logger.error(f"Background cache refresh failed: {e}")


async def apply_schema_partitioning(data: Dict[str, Any]) -> Dict[str, Any]:
    """Rewrite a ``tools/list`` response to the proxy's compact format.

    Responsible for:
    - Merging ProcessManager HOT tools into the Gateway tool list
    - Partitioning JSON schemas through :mod:`schema_partitioner`
    - Shortening descriptions per ``settings.DESCRIPTION_MODE``
    - Injecting the synthetic ``expandSchema`` tool
    - In ``DYNAMIC_MCP`` mode, replacing the full tool list with meta-tools
      + the currently active subset

    Mutates ``data`` in place and returns it.
    """
    if "result" not in data or "tools" not in data["result"]:
        return data

    docker_tools = list(data["result"]["tools"])
    process_manager = get_process_manager()

    # Dynamic MCP mode: meta-tools + HOT server tools with full schema.
    # COLD servers are accessed directly via airis-exec.
    if settings.DYNAMIC_MCP:
        dynamic_mcp = get_dynamic_mcp()
        dynamic_mcp.refresh_toolsets(process_manager)
        excluded_servers = {"airis-mcp-gateway-control", "airis-commands"}

        # HOT servers: expose full schema directly, in parallel with a
        # per-server timeout so a single broken server cannot stall the
        # whole tools/list response.
        hot_tools_list: list[dict] = []
        try:
            hot_servers = [
                s for s in process_manager.get_hot_servers()
                if s not in excluded_servers
            ]

            async def get_tools_for_server(name: str) -> list[dict]:
                try:
                    return await asyncio.wait_for(
                        process_manager.list_tools(server_name=name),
                        timeout=10.0,
                    )
                except asyncio.TimeoutError:
                    logger.warning(f"Timeout listing tools for {name}, skipping")
                    return []
                except Exception as e:
                    logger.error(f"Error listing tools for {name}: {e}")
                    return []

            results = await asyncio.gather(
                *[get_tools_for_server(s) for s in hot_servers]
            )
            for server_tools in results:
                hot_tools_list.extend(server_tools)
        except Exception as e:
            logger.error(f"Failed to list HOT tools: {e}")

        tools = list(dynamic_mcp.get_meta_tools(mode=settings.META_TOOLS_MODE))
        meta_count = len(tools)

        # Lazy Schema: strip every HOT tool's inputSchema down to
        # {"type": "object"} before exposing it. The full schema remains in
        # schema_partitioner / DynamicMCP caches and is served on demand via
        # airis-schema or injected into -32602 error payloads on retry. Copy
        # each dict first so we do not mutate ProcessRunner's cached tools.
        if settings.SCHEMA_MODE == "lazy":
            hot_tools_list = [
                {**t, "inputSchema": {"type": "object"}}
                for t in hot_tools_list
            ]

        tools.extend(hot_tools_list)

        data["result"]["tools"] = tools
        hot_count = len(tools) - meta_count
        logger.info(f"Returning {len(tools)} tools ({meta_count} meta + {hot_count} native)")

        # Schedule background cache refresh (non-blocking)
        asyncio.create_task(_refresh_dynamic_mcp_cache(process_manager, docker_tools))

        return data

    # Standard mode: merge HOT tools and apply schema partitioning
    tools = docker_tools

    try:
        process_tools = await process_manager.list_tools(mode="hot")
        hot_servers = process_manager.get_hot_servers()
        cold_servers = process_manager.get_cold_servers()
        if process_tools:
            logger.info(
                f"Merging {len(process_tools)} HOT tools with {len(tools)} docker tools"
            )
            logger.info(
                f"HOT servers: {hot_servers}, COLD servers (not included): {cold_servers}"
            )
            tools.extend(process_tools)
    except Exception as e:
        logger.error(f"Failed to get process tools: {e}")

    partitioned_tools: list[dict] = []

    for tool in tools:
        tool_name = tool.get("name", "")
        input_schema = tool.get("inputSchema", {})

        if input_schema:
            schema_partitioner.store_full_schema(tool_name, input_schema)

        full_description = tool.get("description")
        schema_partitioner.store_tool_description(tool_name, full_description)
        lightweight_description = summarize_description(
            full_description or "",
            mode=settings.DESCRIPTION_MODE,
        )

        partitioned_schema = schema_partitioner.partition_schema(input_schema)
        reduction = schema_partitioner.get_token_reduction_estimate(input_schema)
        logger.debug(
            f" {tool_name}: {reduction['full']} → {reduction['partitioned']} tokens "
            f"({reduction['reduction']}% reduction)"
        )

        extensions = dict(tool.get("extensions", {}))
        if full_description:
            extensions["hasDocs"] = True
            extensions["docHandle"] = tool_name
            extensions["docHint"] = (
                "Call expandSchema with mode='docs' for the full instructions."
            )
        else:
            extensions["hasDocs"] = False

        partitioned_tool = {
            **tool,
            "inputSchema": partitioned_schema,
            "extensions": extensions,
        }

        if settings.DESCRIPTION_MODE == DescriptionMode.NONE:
            partitioned_tool.pop("description", None)
        elif lightweight_description:
            partitioned_tool["description"] = lightweight_description

        partitioned_tools.append(partitioned_tool)

    # Expose expandSchema as a synthetic tool so clients can lazy-load
    # the real schemas and docs that we partitioned out above.
    expand_schema_tool = {
        "name": "expandSchema",
        "description": (
            "Lazy-load schemas or documentation for a specific tool. "
            "Use mode='schema' (default) for JSON schema or mode='docs' "
            "for the full description."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "toolName": {
                    "type": "string",
                    "description": (
                        "Name of the tool whose schema or docs you want to expand"
                    ),
                },
                "path": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": (
                        "Path to the property to expand (e.g., ['metadata', 'shipping']). "
                        "Omit for full schema."
                    ),
                },
                "mode": {
                    "type": "string",
                    "enum": ["schema", "docs"],
                    "description": (
                        "schema → return JSON schema (default). "
                        "docs → return stored description text."
                    ),
                },
            },
            "required": ["toolName"],
        },
    }
    partitioned_tools.append(expand_schema_tool)

    data["result"]["tools"] = partitioned_tools
    return data
